# Estas son las opciones de financiación compatibles con GitHub Sponsors

github: # Reemplaza con hasta 4 nombres de usuario de GitHub. Estos aparecerán en un botón de patrocinador en tu repositorio
# patreon: # Reemplaza con un nombre de usuario de Patreon
# open_collective: # Reemplaza con un nombre de usuario de Open Collective
# ko_fi: # Reemplaza con un nombre de usuario de Ko-fi
# tidelift: # Reemplaza con un nombre de usuario de Tidelift
# community_bridge: # Reemplaza con un nombre de usuario de Community Bridge
# liberapay: # Reemplaza con un nombre de usuario de Liberapay
# issuehunt: # Reemplaza con un nombre de usuario de IssueHunt
# otechie: # Reemplaza con un nombre de usuario de Otechie
# lfx_crowdfunding: # Reemplaza con un nombre de usuario de LFX Crowdfunding
# custom: # Reemplaza con hasta 4 URLs personalizadas


